package net.gseek.proxima.domain

import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import org.hibernate.Hibernate

/**
 * Identity and equality for every entity here.
 *
 * **These entities are not `data class`es, and that is the whole point.**
 *
 * Kotlin's generated `equals` reads the constructor properties as *fields*. A lazily
 * loaded association is not the entity — it is a Hibernate proxy, a generated subclass
 * whose fields are empty until a getter is called. So a generated `equals` comparing a
 * proxy against a loaded instance of the same database row returns `false`, and every
 * `Set`, `contains`, and `distinct` in the codebase becomes quietly wrong.
 *
 * The generated `hashCode` is worse, because it breaks a contract rather than an
 * expectation: it is computed from all properties including `id`, and `id` is `null`
 * before persist and a number afterwards. An entity put into a `HashSet` and then saved
 * cannot be found in that set again — the hash it was filed under no longer exists.
 *
 * So:
 *
 * - **`equals` compares by `id`, and only once an `id` exists.** Two unsaved instances are
 *   equal only if they are the same object. Anything else would make every new entity
 *   equal to every other new entity.
 * - **The type check goes through `Hibernate.getClass`, not `javaClass`.** A proxy's
 *   `javaClass` is the generated subclass, so `javaClass != other.javaClass` reports two
 *   different types for one row. `Hibernate.getClass` unwraps the proxy first.
 * - **`hashCode` is constant per type.** The contract is that an object's hash does not
 *   change while it lives, and an entity whose `id` arrives later cannot satisfy that any
 *   other way. It costs hash distribution within one entity type, which is not a cost
 *   worth caring about at the collection sizes an entity graph produces.
 *
 * `T3` reproduces the `data class` version of this and measures what it breaks. This class
 * is the state in which it is not broken.
 */
@MappedSuperclass
abstract class BaseEntity {

    /**
     * `IDENTITY` matches `V1`'s `generated by default as identity`. **Decided, measured, and
     * closed by `ADR-003` on 2026-08-13** — it was provisional here for three days.
     *
     * `IDENTITY` forces Hibernate to execute every insert immediately so it can read the
     * generated key back, so inserts cannot be batched. Measured, 1,000 rows with
     * `hibernate.jdbc.batch_size = 50` configured:
     *
     * | generator | statements | median ms |
     * | --- | --- | --- |
     * | `IDENTITY` | 1000 | 290 |
     * | `SEQUENCE`, `allocationSize = 1` | 1020 | 262 |
     * | `SEQUENCE`, `allocationSize = 50` | 40 | 31 |
     *
     * About ten times, and **the gain is the allocation size, not the sequence** — the
     * default `allocationSize = 1` is indistinguishable from what is here now.
     *
     * It stays because nothing in this application inserts more than one row per
     * transaction, so there is nowhere to spend the ten times, and switching would move a
     * reproduced collision hazard from a test into the seed loader. `ADR-003` names what
     * flips it and `IdentifierGenerationTest` goes red if the premise stops holding.
     *
     * **The live consequence: `hibernate.jdbc.batch_size` is inert here and nothing warns.**
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null) return false
        if (Hibernate.getClass(this) != Hibernate.getClass(other)) return false
        val otherId = (other as BaseEntity).id
        return id != null && id == otherId
    }

    override fun hashCode(): Int = Hibernate.getClass(this).hashCode()

    override fun toString(): String =
        "${Hibernate.getClass(this).simpleName}(id=$id)"
}
