-- V1 — baseline schema.
--
-- READ docs/decisions/adr/ADR-002-schema-tells-the-story.md BEFORE ADDING AN INDEX HERE.
--
-- This migration contains primary keys, foreign keys, check constraints, and the unique
-- constraints that identify a row. It deliberately contains NO performance index, and
-- deliberately omits ONE constraint the domain requires.
--
-- That is not an oversight. Every later migration that adds an index or a constraint is
-- paired with a report that measured the system without it first. An index added here
-- would erase the measurement it was supposed to justify.
--
-- Naming: uk_ unique, fk_ foreign key, ck_ check, ix_ index (none yet, by design).

-- ---------------------------------------------------------------------------
-- learner
-- ---------------------------------------------------------------------------
create table learner (
    id           bigint generated by default as identity primary key,
    external_ref varchar(64)  not null,
    created_at   timestamptz  not null default now(),

    constraint uk_learner_external_ref unique (external_ref)
);

comment on table  learner              is 'A person learning. Generated reference only -- no name, no contact, no demographic. See PUB-7.';
comment on column learner.external_ref is 'Opaque generated reference, shaped so it cannot be mistaken for a real identifier.';

-- ---------------------------------------------------------------------------
-- concept  /  concept_edge  (prerequisite DAG)
-- ---------------------------------------------------------------------------
create table concept (
    id         bigint generated by default as identity primary key,
    code       varchar(32)  not null,
    name       varchar(200) not null,
    grade_band varchar(16)  not null,
    created_at timestamptz  not null default now(),

    constraint uk_concept_code unique (code)
);

create table concept_edge (
    id              bigint generated by default as identity primary key,
    prerequisite_id bigint       not null,
    concept_id      bigint       not null,
    weight          numeric(4,3) not null default 1.000,

    constraint fk_concept_edge_prerequisite foreign key (prerequisite_id) references concept (id),
    constraint fk_concept_edge_concept      foreign key (concept_id)      references concept (id),
    constraint uk_concept_edge              unique (prerequisite_id, concept_id),
    constraint ck_concept_edge_no_self      check  (prerequisite_id <> concept_id),
    constraint ck_concept_edge_weight       check  (weight > 0 and weight <= 1)
);

comment on table concept_edge is
    'prerequisite_id must be understood before concept_id. A DAG, not a tree. '
    'Acyclicity is asserted by the generator and checked by a test -- a CHECK constraint '
    'cannot express it, and that gap is recorded rather than hidden.';

-- ---------------------------------------------------------------------------
-- item  /  item_concept
-- ---------------------------------------------------------------------------
create table item (
    id                 bigint      generated by default as identity primary key,
    code               varchar(32) not null,
    concept_primary_id bigint      not null,
    difficulty         smallint    not null,
    is_active          boolean     not null default true,
    created_at         timestamptz not null default now(),

    constraint fk_item_concept_primary foreign key (concept_primary_id) references concept (id),
    constraint uk_item_code            unique (code),
    constraint ck_item_difficulty      check  (difficulty between 1 and 10)
);

create table item_concept (
    item_id    bigint       not null,
    concept_id bigint       not null,
    weight     numeric(4,3) not null default 1.000,

    constraint pk_item_concept      primary key (item_id, concept_id),
    constraint fk_item_concept_item foreign key (item_id)    references item (id),
    constraint fk_item_concept_cpt  foreign key (concept_id) references concept (id),
    constraint ck_item_concept_wt   check  (weight > 0 and weight <= 1)
);

-- ---------------------------------------------------------------------------
-- attempt  -- the hot table
-- ---------------------------------------------------------------------------
--
-- Three million rows. Append-only. Every read is scoped to one learner and ordered by
-- time. There is NO index on (learner_id, attempted_at) yet, and that absence is the
-- starting point of the indexing report -- the first EXPLAIN in this repository is
-- supposed to show a sequential scan.
--
create table attempt (
    id           bigint      generated by default as identity primary key,
    learner_id   bigint      not null,
    item_id      bigint      not null,
    correct      boolean     not null,
    elapsed_ms   integer     not null,
    hint_used    boolean     not null default false,
    attempted_at timestamptz not null,

    constraint fk_attempt_learner foreign key (learner_id) references learner (id),
    constraint fk_attempt_item    foreign key (item_id)    references item (id),
    constraint ck_attempt_elapsed check  (elapsed_ms >= 0)
);

comment on column attempt.elapsed_ms is
    'Time on task. Kept because accuracy alone cannot distinguish "knew it" from '
    '"guessed it" -- the variance of this column carries more signal than its mean.';
comment on column attempt.hint_used is
    'Whether a hint was opened before answering. A correct answer after a hint is a '
    'different event from a correct answer without one.';

-- ---------------------------------------------------------------------------
-- mastery
-- ---------------------------------------------------------------------------
--
-- DELIBERATELY MISSING: unique (learner_id, concept_id).
--
-- The domain requires it -- a learner has exactly one mastery row per concept. It is
-- absent here so that the race it permits can be reproduced and measured: two concurrent
-- requests both run an application-level existence check, both pass, and both insert.
--
-- The constraint arrives in a later migration, in the same commit as the failing test and
-- the report. Adding it now would make that report unwritable. See ADR-002.
--
-- `version` is present from the start because it is the optimistic-locking column, and
-- comparing locking strategies is one of the things this schema exists to support.
--
create table mastery (
    id             bigint       generated by default as identity primary key,
    learner_id     bigint       not null,
    concept_id     bigint       not null,
    score          numeric(4,3) not null default 0.000,
    attempts_count integer      not null default 0,
    version        bigint       not null default 0,
    updated_at     timestamptz  not null default now(),

    constraint fk_mastery_learner foreign key (learner_id) references learner (id),
    constraint fk_mastery_concept foreign key (concept_id) references concept (id),
    constraint ck_mastery_score   check  (score >= 0 and score <= 1),
    constraint ck_mastery_count   check  (attempts_count >= 0)
);

comment on column mastery.version is 'Optimistic locking. See the concurrency report.';
