-- V5 — acyclicity, as a CHECK constraint, which V1 says is impossible.
--
-- READ docs/decisions/adr/ADR-010-where-a-cycle-is-refused.md BEFORE CHANGING THIS.
-- The measurement that justifies it is docs/reports/R21.
--
-- WHAT V1 SAYS, AND WHY IT IS TRUE AND MISLEADING AT THE SAME TIME.
--
--   `comment on table concept_edge` has said this since the first commit:
--
--     'Acyclicity is asserted by the generator and checked by a test -- a CHECK constraint
--      cannot express it, and that gap is recorded rather than hidden.'
--
--   Every word of that is correct about acyclicity IN GENERAL. A CHECK sees one row; a cycle
--   is a property of the whole graph; no per-row predicate can see one. R21 measured what a
--   trigger -- which CAN see the graph -- costs and what it still cannot promise:
--
--     added per inserted row      2.33 ms  (batched)  /  2.20 ms  (set-based)
--     two concurrent inserts      both pass, both commit, the graph has a cycle
--
--   The second line is the one that matters. Each transaction checks a graph in which the
--   other's edge does not exist, exactly as R7's two requests each passed an existence check.
--   V3 could close R7 with a unique constraint because UNIQUENESS IS A PROPERTY OF A ROW.
--   Acyclicity is not, so a trigger reduces the window and cannot close it.
--
--   AND YET THIS SCHEMA CAN HAVE THE GUARANTEE FOR NOTHING, because the generator already
--   holds something stronger and nobody had written it down as a constraint:
--
--     Generator.writeConceptEdges: "Every edge runs from a lower concept id to a higher one."
--
--   If every edge satisfies `prerequisite_id < concept_id`, then walking prerequisites
--   strictly decreases the id at every hop, so a walk cannot return to where it started.
--   That is a proof of acyclicity, and it is a PER-ROW predicate. A CHECK can hold it.
--
--   So V1's comment is true about the general problem and wrong about this schema, and it
--   was read as the second for eleven days. That is the class of statement this repository
--   exists to catch, and it was in its own baseline.
--
-- WHAT THIS COSTS, STATED BLUNTLY BECAUSE IT IS NOT SMALL.
--
--   The constraint welds acyclicity to the surrogate key. `concept.id` is
--   `generated by default as identity`, so a new concept always gets a HIGHER id than every
--   existing one -- and therefore CAN NEVER BE MADE A PREREQUISITE OF AN EXISTING CONCEPT.
--   A curriculum author who realises that fractions belong before division cannot say so.
--
--   That is acceptable today for one reason and it is a reason with a shelf life: there is
--   no curriculum-editing path in this application. `concept_edge` has exactly one writer,
--   `seed/`'s loader, and it emits forward edges by construction. The constraint protects
--   data that exists rather than data somebody might write, which is the test ADR-007 used
--   to decline a guard and the test this one passes.
--
--   THE MIGRATION THAT LIFTS THIS is not a `drop constraint`. It needs an explicit ordering
--   column on `concept` -- a `sequence_no` that is not the primary key -- so that the
--   ordering the graph depends on stops being an accident of insertion order. ADR-010 names
--   that as the condition, and it needs its own report.
--
-- WHY THERE IS NO CLEANUP STEP, UNLIKE V3.
--
--   V3 deleted duplicate `mastery` rows before adding its unique constraint, because a
--   database in the wild might hold them. This one deliberately does not: `ALTER TABLE ...
--   ADD CONSTRAINT ... CHECK` scans the table and FAILS on a violating row, and failing is
--   correct here. A backwards edge is a curriculum statement somebody made. Deleting it
--   silently to let a migration through would be exactly the domain decision V3's own
--   comment refuses to make, and the row it deleted would be the one worth looking at.
--
--   The failure a reader would get names the constraint and the table, and R21 is what to
--   read next.

alter table concept_edge
    add constraint ck_concept_edge_forward check (prerequisite_id < concept_id);

comment on constraint ck_concept_edge_forward on concept_edge is
    'Acyclicity, as a row predicate. Walking prerequisites strictly decreases concept.id, so '
    'no walk can return to its start. This is stronger than the domain requires and it is '
    'what the generator already guaranteed; the cost is that a new concept can never become '
    'a prerequisite of an older one. See ADR-010 and docs/reports/R21.';

comment on table concept_edge is
    'prerequisite_id must be understood before concept_id. A DAG, not a tree. '
    'Acyclicity IS enforced, by ck_concept_edge_forward (V5): every edge runs from a lower '
    'concept id to a higher one, so a prerequisite walk strictly decreases and cannot cycle. '
    'This comment previously said a CHECK constraint cannot express acyclicity -- true of the '
    'general problem, false of this schema, and read as the second for eleven days. '
    'docs/reports/R21 and ADR-010.';
