package net.gseek.proxima.seed

import java.nio.file.Files
import java.nio.file.Path
import java.sql.Connection
import java.sql.DriverManager
import org.postgresql.copy.CopyManager
import org.postgresql.core.BaseConnection

/**
 * Loads the generated files into PostgreSQL with `COPY`.
 *
 * **`COPY`, and never a row-at-a-time `INSERT` loop.** At three million rows that choice is
 * the difference between minutes and tens of minutes, and it is the reason regenerating the
 * dataset is cheap enough that `PUB-7`'s "the seed is code" survives contact with an
 * impatient afternoon.
 *
 * **The column list is written out for every table on purpose.** `COPY` without one binds
 * to the table's current column order, so adding a column to a migration would silently
 * shift every field of a load that still appeared to work. Naming the columns turns that
 * into an error.
 */
class Loader(private val jdbcUrl: String, private val user: String, private val password: String) {

    fun connect(): Connection = DriverManager.getConnection(jdbcUrl, user, password)

    /** Table name to the column list its `.tsv` file is written in. Load order matters. */
    private val columns: List<Pair<String, String>> = listOf(
        "learner" to "id, external_ref, created_at",
        "concept" to "id, code, name, grade_band, created_at",
        "concept_edge" to "id, prerequisite_id, concept_id, weight",
        "item" to "id, code, concept_primary_id, difficulty, is_active, created_at",
        "item_concept" to "item_id, concept_id, weight",
        "attempt" to "id, learner_id, item_id, correct, elapsed_ms, hint_used, attempted_at",
        "mastery" to "id, learner_id, concept_id, score, attempts_count, version, updated_at",
    )

    fun loadAll(dir: Path): Map<String, Long> {
        val loaded = LinkedHashMap<String, Long>()
        connect().use { conn ->
            conn.autoCommit = false
            val copy = CopyManager(conn.unwrap(BaseConnection::class.java))
            for ((table, cols) in columns) {
                val file = dir.resolve("$table.tsv")
                val started = System.nanoTime()
                val rows = Files.newInputStream(file).use { input ->
                    copy.copyIn("copy $table ($cols) from stdin", input)
                }
                val ms = (System.nanoTime() - started) / 1_000_000
                loaded[table] = rows
                println("  copy %-13s %,12d rows  %,7d ms".format(table, rows, ms))
            }
            conn.commit()
        }
        return loaded
    }

    /**
     * Realigns each identity sequence with the ids that were just loaded.
     *
     * **Skipping this leaves a database that passes every check and then fails on the
     * first insert.** The columns are `generated by default as identity`, which is what
     * permits `COPY` to supply explicit ids at all — but the sequence behind the column
     * does not advance when ids arrive that way. It is still sitting at 1, so the first
     * application insert asks for id 1, which the primary key already holds. Nothing about
     * the load looks wrong; the row counts are right and every foreign key resolves.
     *
     * `item_concept` is absent because its key is `(item_id, concept_id)` and it has no
     * identity column.
     */
    fun realignSequences() {
        val tables = listOf("learner", "concept", "concept_edge", "item", "attempt", "mastery")
        connect().use { conn ->
            conn.createStatement().use { st ->
                for (t in tables) {
                    st.execute(
                        "select setval(pg_get_serial_sequence('$t', 'id'), " +
                            "coalesce((select max(id) from $t), 1))",
                    )
                }
            }
        }
        println("  sequences realigned for ${tables.joinToString(", ")}")
    }

    fun analyze() {
        connect().use { conn ->
            conn.createStatement().use { st ->
                val started = System.nanoTime()
                st.execute("analyze")
                println("  analyze  %,7d ms".format((System.nanoTime() - started) / 1_000_000))
            }
        }
    }

    fun truncateAll() {
        connect().use { conn ->
            conn.createStatement().use { st ->
                st.execute(
                    "truncate attempt, mastery, item_concept, item, concept_edge, concept, learner " +
                        "restart identity cascade",
                )
            }
        }
        println("  truncated")
    }

    fun rowCounts(): Map<String, Long> {
        val counts = LinkedHashMap<String, Long>()
        connect().use { conn ->
            conn.createStatement().use { st ->
                for ((table, _) in columns) {
                    st.executeQuery("select count(*) from $table").use { rs ->
                        rs.next()
                        counts[table] = rs.getLong(1)
                    }
                }
            }
        }
        return counts
    }
}
