package net.gseek.proxima.db

import java.sql.Connection
import java.sql.DriverManager
import kotlin.test.assertTrue
import net.gseek.proxima.TestcontainersConfiguration.Companion.POSTGRES_IMAGE
import org.flywaydb.core.Flyway
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.testcontainers.postgresql.PostgreSQLContainer
import org.testcontainers.utility.DockerImageName

/**
 * `T8` — what an in-memory database does not tell you, measured against **this repository's
 * own migrations and statements** rather than against invented examples.
 *
 * ## Why both databases, and not H2 alone
 *
 * Running the statements on H2 and counting the failures answers the easy half of the
 * question. A statement that throws on H2 is a statement someone notices. The half that
 * matters is the statement that **succeeds on both and answers differently**, because there
 * is no exception, no warning, and no reason for anyone to look. So every probe below runs
 * against H2 *and* against the pinned PostgreSQL this repository actually ships on, and the
 * two answers are compared rather than the H2 answer being judged on its own.
 *
 * That splits the findings into three kinds:
 *
 * | kind | meaning |
 * | --- | --- |
 * | `AGREE` | both accept, same answer — H2 tells the truth about this statement |
 * | `LOUD` | one refuses — a build breaks, and someone finds out |
 * | `SILENT` | both accept, different answers — **nothing tells anyone** |
 *
 * PostgreSQL is the control, not the subject. It is here so that a failure is attributable
 * to H2 rather than to a probe that was wrong to begin with — the same reason `R5`'s log
 * appender had to prove it could capture an event before its silence meant anything.
 *
 * ## No Spring context
 *
 * Flyway and JDBC directly, so a result is attributable to the database rather than to
 * autoconfiguration. H2 runs in its PostgreSQL compatibility mode, which is what someone
 * choosing H2 *because it behaves like PostgreSQL* would pick; measuring it in its own
 * dialect would be a straw man.
 *
 * ## Nothing here asserts a pass
 *
 * Both outcomes of every probe are a finding, so the tests fail only if they could not run.
 * The numbers are read out of the printed tables into `docs/reports/R9`.
 */
class H2DivergenceTest {

    // ---------------------------------------------------------------------------------
    // The two databases
    // ---------------------------------------------------------------------------------

    companion object {
        private lateinit var pg: PostgreSQLContainer

        @BeforeAll
        @JvmStatic
        fun startPostgres() {
            pg = PostgreSQLContainer(DockerImageName.parse(POSTGRES_IMAGE))
            pg.start()
        }

        @AfterAll
        @JvmStatic
        fun stopPostgres() {
            if (::pg.isInitialized) pg.stop()
        }
    }

    private enum class Db(val label: String) { H2("H2"), PG("PostgreSQL") }

    /**
     * A fresh, empty database for one probe.
     *
     * Per-probe isolation is not tidiness. H2 commits DDL implicitly, so a probe that
     * creates a table cannot be rolled back, and a probe that deletes rows would change what
     * the next one measures. Isolating them is what makes each row of the table below
     * independent of the order the rows are in.
     */
    private fun <T> fresh(db: Db, block: (Connection) -> T): T = when (db) {
        Db.H2 -> DriverManager.getConnection(
            "jdbc:h2:mem:t8_${System.nanoTime()};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
            "sa",
            "",
        )
        Db.PG -> DriverManager.getConnection(pg.jdbcUrl, pg.username, pg.password)
    }.use { conn ->
        if (db == Db.PG) {
            conn.createStatement().use { it.execute("drop table if exists t8_mastery cascade") }
            conn.createStatement().use { it.execute("drop table if exists t8_probe cascade") }
        }
        block(conn)
    }

    /**
     * The smallest schema the probes need, in **portable** DDL.
     *
     * Deliberately not this repository's own `V1`: `V1` does not survive H2 at all (the
     * migration probe below measures exactly that), and if the schema could not be created
     * then no statement could be measured and the interesting half of the question would go
     * unanswered. So the types here are the ones both databases accept, and what is being
     * measured is the *statements*, not the DDL.
     */
    private fun seed(c: Connection) {
        c.createStatement().use { st ->
            st.execute(
                """
                create table t8_mastery (
                    id             bigint       generated by default as identity primary key,
                    learner_id     bigint       not null,
                    concept_id     bigint       not null,
                    score          numeric(4,3) not null default 0.000,
                    attempts_count integer      not null default 0,
                    version        bigint       not null default 0,
                    is_active      boolean      not null default true,
                    label          varchar(50)  not null default '',
                    updated_at     timestamp    not null default current_timestamp,
                    constraint uk_t8_mastery unique (learner_id, concept_id)
                )
                """.trimIndent(),
            )
            // Four labels chosen to separate a case-sensitive collation from a
            // case-insensitive one: binary ordering puts every capital before every
            // lower-case letter, a linguistic collation interleaves them.
            st.execute(
                "insert into t8_mastery (learner_id, concept_id, label) values " +
                    "(1, 1, 'apple'), (1, 2, 'Banana'), (1, 3, 'cherry'), (1, 4, 'Apple')",
            )
        }
    }

    // ---------------------------------------------------------------------------------
    // Probes -- every one of them is a statement this repository actually issues
    // ---------------------------------------------------------------------------------

    /**
     * @param origin the file or report the statement comes from. A probe that cannot name
     *   where the statement lives is a probe about H2 in general, which is not the question.
     * @param needsSchema false for probes that create their own table, so a DDL probe is not
     *   hidden behind a schema that already failed to build.
     */
    private class Probe(
        val name: String,
        val origin: String,
        val needsSchema: Boolean = true,
        val run: (Connection) -> String,
    )

    private fun one(c: Connection, sql: String): String =
        c.createStatement().use { st ->
            st.executeQuery(sql).use { rs ->
                if (!rs.next()) "no rows" else rs.getString(1) ?: "null"
            }
        }

    private val probes = listOf(
        Probe("timestamptz (the abbreviation)", "V1, every created_at", needsSchema = false) { c ->
            c.createStatement().use { it.execute("create table t8_probe (c timestamptz)") }
            "accepted"
        },
        Probe("timestamp with time zone (spelled out)", "V1, if it were portable", needsSchema = false) { c ->
            c.createStatement().use { it.execute("create table t8_probe (c timestamp with time zone)") }
            "accepted"
        },
        Probe("adjacent string literals across lines", "V1 + V3 comments") { c ->
            one(c, "select 'first '\n'second'")
        },
        Probe("comment on column", "V1, 6 of them") { c ->
            c.createStatement().use { it.execute("comment on column t8_mastery.score is 'x'") }
            "accepted"
        },
        Probe("comment on constraint ... on <table>", "V3, last statement") { c ->
            c.createStatement().use {
                it.execute("comment on constraint uk_t8_mastery on t8_mastery is 'x'")
            }
            "accepted"
        },
        Probe("delete with a correlated alias", "V3, the deduplication") { c ->
            val n = c.createStatement().use {
                it.executeUpdate(
                    """
                    delete from t8_mastery m
                     where m.id > (select min(m2.id) from t8_mastery m2
                                    where m2.learner_id = m.learner_id
                                      and m2.concept_id = m.concept_id)
                    """.trimIndent(),
                )
            }
            "$n rows deleted"
        },
        Probe("insert ... on conflict do nothing", "MasteryProvisioner, R7") { c ->
            val n = c.createStatement().use {
                it.executeUpdate(
                    "insert into t8_mastery (learner_id, concept_id) values (1, 1) " +
                        "on conflict (learner_id, concept_id) do nothing",
                )
            }
            "$n rows inserted"
        },
        Probe("insert ... on conflict do update ... excluded", "R7 §5, the upsert arm") { c ->
            val n = c.createStatement().use {
                it.executeUpdate(
                    "insert into t8_mastery (learner_id, concept_id, attempts_count) values (1, 1, 9) " +
                        "on conflict (learner_id, concept_id) " +
                        "do update set attempts_count = excluded.attempts_count",
                )
            }
            "$n rows affected, attempts_count=" + one(c, "select attempts_count from t8_mastery where id = 1")
        },
        Probe("a constraint violation aborts the transaction", "R7 §4 — the whole mechanism") { c ->
            c.autoCommit = false
            try {
                val duplicateAccepted = try {
                    c.createStatement().use {
                        it.execute("insert into t8_mastery (learner_id, concept_id) values (1, 1)")
                    }
                    true
                } catch (_: Exception) {
                    false // expected on both -- what matters is the state left behind
                }
                if (duplicateAccepted) {
                    "the duplicate was ACCEPTED"
                } else {
                    // PostgreSQL: 25P02, everything until rollback is refused -- which is why
                    // R7's catch-and-continue arm failed 7 of 8. H2 leaves the session usable.
                    try {
                        one(c, "select count(*) from t8_mastery")
                        "the next statement SUCCEEDED"
                    } catch (e: Exception) {
                        "the next statement was REFUSED (${sqlState(e)})"
                    }
                }
            } finally {
                runCatching { c.rollback() }
                c.autoCommit = true
            }
        },
        Probe("pg_stat_user_tables", "R5, R8 — statement counting") { c ->
            one(c, "select count(*) from pg_stat_user_tables")
            "readable"
        },
        Probe("pg_stat_activity.backend_type", "R2, R4 — pool occupancy") { c ->
            one(c, "select count(*) from pg_stat_activity where backend_type = 'client backend'")
            "readable"
        },
        Probe("explain (analyze, buffers)", "R2, R3 — every plan in this repo") { c ->
            one(c, "explain (analyze, buffers) select count(*) from t8_mastery")
            "accepted"
        },
        Probe("select ... for update", "R6 §3, the pessimistic arm") { c ->
            c.autoCommit = false
            try {
                one(c, "select attempts_count from t8_mastery where id = 1 for update")
                "accepted"
            } finally {
                c.rollback()
                c.autoCommit = true
            }
        },
        Probe("update ... set x = x + 1", "R6 §3, the atomic arm — the one that won") { c ->
            c.createStatement().use {
                it.executeUpdate("update t8_mastery set attempts_count = attempts_count + 1 where id = 1")
            }
            "attempts_count=" + one(c, "select attempts_count from t8_mastery where id = 1")
        },
        // OPEN-3's recorded hazard, and the only probe here for a statement this repository
        // does not issue *yet*: the loader that realigns the identity sequence after a bulk
        // load does not exist. It is included because OPEN-3 says the decision is due before
        // that loader is written, and this is one of the facts the decision needs.
        //
        // `COPY ... FROM STDIN` is deliberately NOT probed. On PostgreSQL it is a driver API
        // (`CopyManager`), not a statement, so a SQL-level probe would fail on both databases
        // and print a row implying PostgreSQL cannot do it. Recorded as unmeasured instead.
        Probe("setval(pg_get_serial_sequence(...))", "OPEN-3, the loader not yet written") { c ->
            one(c, "select setval(pg_get_serial_sequence('t8_mastery','id'), 100)")
            "accepted"
        },
        Probe("a bare boolean column as a predicate", "RecommendationQueries: `and i.is_active`") { c ->
            "rows=" + one(c, "select count(*) from t8_mastery where is_active")
        },
        Probe("a quoted mixed-case alias", "RecommendationQueries: `as \"itemCode\"`") { c ->
            c.createStatement().use { st ->
                st.executeQuery("select id as \"itemCode\" from t8_mastery where id = 1").use { rs ->
                    rs.next()
                    "label=" + rs.metaData.getColumnLabel(1)
                }
            }
        },
        Probe("ordering of mixed-case text", "any `order by` on a name column") { c ->
            c.createStatement().use { st ->
                st.executeQuery("select label from t8_mastery order by label").use { rs ->
                    buildList { while (rs.next()) add(rs.getString(1)) }.joinToString(",")
                }
            }
        },
        // The control for the row above. If the default ordering is byte order because that
        // is all this image can do, then naming a linguistic collation explicitly changes the
        // answer -- and the previous row's AGREE is a fact about the container, not about the
        // two databases. If it does not change, the AGREE means what it appears to mean.
        Probe("the same order by, told which collation", "the control for the row above") { c ->
            c.createStatement().use { st ->
                st.executeQuery("select label from t8_mastery order by label collate \"en-US-x-icu\"")
                    .use { rs -> buildList { while (rs.next()) add(rs.getString(1)) }.joinToString(",") }
            }
        },
        Probe("numeric(4,3) rounding on insert", "mastery.score everywhere") { c ->
            c.createStatement().use {
                it.executeUpdate("insert into t8_mastery (learner_id, concept_id, score) values (2, 1, 0.12349)")
            }
            "score=" + one(c, "select score from t8_mastery where learner_id = 2")
        },
        Probe("create index on (a, b)", "V2 — the T4 remedy") { c ->
            c.createStatement().use {
                it.execute("create index ix_t8 on t8_mastery (learner_id, updated_at)")
            }
            "accepted"
        },
        // The roadmap names reserved words as one of T8's strands. No column in this schema
        // is currently called any of these, so this probe is about a change someone could
        // make tomorrow rather than about code that exists -- labelled as such.
        Probe("a column named `value`", "roadmap strand; no such column today", needsSchema = false) { c ->
            c.createStatement().use { it.execute("create table t8_probe (value integer not null)") }
            "accepted"
        },
        Probe("a column named `key`", "roadmap strand; no such column today", needsSchema = false) { c ->
            c.createStatement().use { it.execute("create table t8_probe (key integer not null)") }
            "accepted"
        },
    )

    private fun sqlState(e: Throwable): String =
        generateSequence(e) { it.cause }
            .filterIsInstance<java.sql.SQLException>()
            .firstOrNull()
            ?.sqlState
            ?: "?"

    private fun firstLine(e: Throwable): String =
        generateSequence(e) { it.cause }.last().message
            ?.lineSequence()?.firstOrNull()
            ?.take(90)
            ?: e.toString()

    private fun attempt(db: Db, p: Probe): String =
        try {
            fresh(db) { c ->
                if (p.needsSchema) seed(c)
                p.run(c)
            }
        } catch (e: Exception) {
            "!! " + firstLine(e)
        }

    // ---------------------------------------------------------------------------------
    // Tests
    // ---------------------------------------------------------------------------------

    /**
     * What the two databases actually are, printed rather than assumed.
     *
     * **The collation is here because a prediction failed.** Mixed-case ordering was expected
     * to diverge and did not: both databases returned `Apple,Banana,apple,cherry`, which is
     * byte order. That is a true statement about *this* PostgreSQL and it would be a false
     * statement about PostgreSQL in general, so the setting that decides it gets measured and
     * quoted instead of the AGREE being reported as if it settled the question.
     */
    @Test
    fun `what the two databases are`() {
        // `lc_collate` stopped being a readable server setting in PostgreSQL 15; it is a
        // property of the database, and asking the old way fails rather than misreporting.
        val postgres = fresh(Db.PG) { c ->
            listOf(
                "version()",
                "(select datcollate from pg_database where datname = current_database())",
                "(select datctype   from pg_database where datname = current_database())",
                "(select datlocprovider::text from pg_database where datname = current_database())",
                "(select count(*)::text from pg_collation where collprovider = 'i')",
            ).joinToString("\n    ") { expr -> "$expr\n      = " + one(c, "select $expr") }
        }
        val h2 = fresh(Db.H2) { c -> one(c, "select h2version()") }

        println()
        println("T8-ENV >>>")
        println("  PostgreSQL")
        println("    $postgres")
        println("  H2")
        println("    version = $h2")
        println()

        assertTrue(postgres.isNotBlank())
    }

    /**
     * The migrations that ship, applied by Flyway to each database.
     *
     * PostgreSQL is the control. If `V1..V3` did not apply there either, an H2 failure would
     * say nothing about H2.
     */
    @Test
    fun `the migrations that ship`() {
        /**
         * Applying the migrations is only half of it. Flyway reporting success means it
         * executed the files without raising, and `EmbeddedSubstitutionControlTest` found a
         * database where that was true and the tables were still not usable. So the table
         * names are read back **as the database spells them**, from JDBC metadata, and
         * printed rather than counted.
         */
        fun migrateThenList(label: String, url: String, user: String, password: String): String =
            try {
                val fw = Flyway.configure().dataSource(url, user, password).cleanDisabled(false)
                val loaded = fw.locations("classpath:db/migration").load()
                loaded.clean()
                val applied = loaded.migrate().migrationsExecuted
                val tables = DriverManager.getConnection(url, user, password).use { c ->
                    c.metaData.getTables(null, null, "%", arrayOf("TABLE")).use { rs ->
                        buildList { while (rs.next()) add(rs.getString("TABLE_NAME")) }
                            .filterNot { it.equals("flyway_schema_history", ignoreCase = true) }
                            .sorted()
                    }
                }
                "applied $applied migrations; tables = $tables"
            } catch (e: Exception) {
                "!! " + firstLine(e)
            }

        val results = linkedMapOf(
            // The control. If this fails, nothing below is attributable to H2.
            "PostgreSQL 16 (control)" to
                migrateThenList("pg", pg.jdbcUrl, pg.username, pg.password),
            // The mode someone picks *because* they want PostgreSQL behaviour.
            "H2, MODE=PostgreSQL" to migrateThenList(
                "h2-pg",
                "jdbc:h2:mem:t8_mig_pg_${System.nanoTime()};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
                "sa",
                "",
            ),
            // The URL Spring Boot's own embedded-datasource substitution builds -- no mode,
            // no case setting. Nobody types this one; it is what you get.
            "H2, as Spring Boot substitutes it" to migrateThenList(
                "h2-boot",
                "jdbc:h2:mem:t8_mig_boot_${System.nanoTime()};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false",
                "sa",
                "",
            ),
        )

        println()
        println("T8-MIGRATIONS >>>")
        results.forEach { (k, v) -> println("  %-34s : %s".format(k, v)) }
        println()

        assertTrue(
            results.getValue("PostgreSQL 16 (control)").startsWith("applied"),
            "the control failed, so nothing here is attributable to H2",
        )
    }

    /**
     * Every statement this repository issues, on both databases, compared.
     */
    @Test
    fun `the statements this repository issues`() {
        val rows = probes.map { p ->
            val h2 = attempt(Db.H2, p)
            val postgres = attempt(Db.PG, p)
            val kind = when {
                h2 == postgres -> "AGREE"
                h2.startsWith("!!") || postgres.startsWith("!!") -> "LOUD"
                else -> "SILENT"
            }
            listOf(kind, p.name, p.origin, postgres, h2)
        }

        println()
        println("T8-COMPARISON >>>")
        val header = listOf("kind", "statement", "comes from", "PostgreSQL", "H2")
        val widths = (0..4).map { i -> (rows + listOf(header)).maxOf { it[i].length } }
        fun line(cells: List<String>) =
            cells.mapIndexed { i, s -> s.padEnd(widths[i]) }.joinToString("  | ")
        println("  " + line(header))
        println("  " + widths.joinToString("--+-") { "-".repeat(it) })
        rows.sortedBy { listOf("SILENT", "LOUD", "AGREE").indexOf(it[0]) }
            .forEach { println("  " + line(it)) }

        val tally = rows.groupingBy { it[0] }.eachCount()
        println()
        println("T8-TALLY >>> ${probes.size} statements: $tally")
        println()

        assertTrue(rows.isNotEmpty(), "nothing was tried, so nothing was learned")
    }
}
