package net.gseek.proxima.db

import java.sql.Connection
import java.sql.DriverManager
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import net.gseek.proxima.TestcontainersConfiguration.Companion.POSTGRES_IMAGE
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.testcontainers.postgresql.PostgreSQLContainer
import org.testcontainers.utility.DockerImageName

/**
 * **`V3`'s deduplication, run against actual duplicates for the first time.**
 *
 * ## Why this did not exist, and why that mattered
 *
 * `V3` deletes duplicate `mastery` rows and then adds the unique constraint. Every test in
 * this repository applies it **to an empty schema** — Flyway runs at container start, before
 * any fixture inserts anything — so the delete has always run against nothing. It was green
 * everywhere and had never done its job once.
 *
 * `R15` found the cost of that: the original correlated subquery is quadratic on a table with
 * no index on `(learner_id, concept_id)`, which is precisely the table `V3` is called on to
 * fix. Against the seeded database it never finished.
 *
 * Rewriting the statement made this test necessary rather than optional: **swapping one
 * unverified statement for another is not a fix.**
 *
 * ## Why it reads the file
 *
 * The statement under test is taken **out of `V3` on the classpath**, not copied here. A copy
 * drifts, and a drifted copy passes while the migration is wrong — the failure mode `R8` §3.2
 * describes for upper bounds and `R9` §7 for vacuous gates. Only the table name is
 * substituted, so what runs is the shipped text.
 */
class MigrationDeduplicationTest {

    companion object {
        const val TABLE = "t_v3_dedup"

        private lateinit var pg: PostgreSQLContainer

        @BeforeAll
        @JvmStatic
        fun startPostgres() {
            pg = PostgreSQLContainer(DockerImageName.parse(POSTGRES_IMAGE))
            pg.start()
        }

        @AfterAll
        @JvmStatic
        fun stopPostgres() {
            if (::pg.isInitialized) pg.stop()
        }
    }

    private val migration: String =
        checkNotNull(javaClass.getResource("/db/migration/V3__mastery_unique_learner_concept.sql")) {
            "V3 is not on the test classpath, so this test would prove nothing"
        }.readText()

    /**
     * The `delete` statement as `V3` ships it, retargeted at a scratch table.
     *
     * Comment lines are stripped first: `V3`'s commentary contains the *old* statement as an
     * illustration, and a naive scan for `delete from` would find that one instead — which
     * would make this test assert the correctness of the statement it was written to replace.
     */
    private val deleteStatement: String by lazy {
        val sql = migration.lineSequence()
            .filterNot { it.trimStart().startsWith("--") }
            .joinToString("\n")
        val start = sql.indexOf("delete from mastery")
        assertTrue(start >= 0, "V3 no longer contains a `delete from mastery`; this test is stale")
        sql.substring(start, sql.indexOf(';', start) + 1)
            .replace("mastery", TABLE)
    }

    private fun connect(): Connection =
        DriverManager.getConnection(pg.jdbcUrl, pg.username, pg.password)

    @Test
    fun `the shipped deduplication keeps the lowest id of each pair`() {
        connect().use { c ->
            c.createStatement().use { st ->
                st.execute("drop table if exists $TABLE")
                st.execute(
                    """
                    create table $TABLE (
                        id         bigint generated by default as identity primary key,
                        learner_id bigint not null,
                        concept_id bigint not null,
                        score      numeric(4,3) not null default 0.000
                    )
                    """.trimIndent(),
                )
                // (1,1) three times, (1,2) twice, (2,1) once. Scores differ so that the
                // SURVIVING row is identifiable, not merely counted -- V3's own comment says
                // the delete keeps the earliest row rather than merging, and that is a domain
                // decision this test has to be able to see.
                st.execute(
                    "insert into $TABLE (learner_id, concept_id, score) values " +
                        "(1,1,0.100),(1,1,0.200),(1,1,0.300)," +
                        "(1,2,0.400),(1,2,0.500)," +
                        "(2,1,0.600)",
                )
            }

            val before = c.rows(TABLE)
            val removed = c.createStatement().use { it.executeUpdate(deleteStatement) }
            val after = c.rows(TABLE)

            println()
            println("R15-DEDUP >>> the statement V3 ships, against planted duplicates")
            println("  statement : ${deleteStatement.replace(Regex("\\s+"), " ").take(150)}…")
            println("  before    : $before")
            println("  removed   : $removed")
            println("  after     : $after")
            println()

            assertEquals(3, removed, "the wrong number of duplicates was removed: $after")
            assertEquals(
                listOf("1|1|0.100", "1|2|0.400", "2|1|0.600"), after,
                "deduplication did not keep the LOWEST id of each pair. V3's comment says it " +
                    "keeps the earliest row and deliberately does not merge -- if that is no " +
                    "longer true, the migration is making a domain decision it says it is not",
            )
        }
    }

    private fun Connection.rows(table: String): List<String> =
        createStatement().use { st ->
            st.executeQuery("select learner_id, concept_id, score from $table order by id").use { rs ->
                buildList {
                    while (rs.next()) {
                        add("${rs.getLong(1)}|${rs.getLong(2)}|${rs.getBigDecimal(3).toPlainString()}")
                    }
                }
            }
        }
}
