package net.gseek.proxima.db

import java.sql.Connection
import java.sql.DriverManager
import kotlin.test.assertTrue
import net.gseek.proxima.TestcontainersConfiguration.Companion.POSTGRES_IMAGE
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.testcontainers.postgresql.PostgreSQLContainer
import org.testcontainers.utility.DockerImageName

/**
 * **Did this repository's own dataset hide a strand of `T4`?**
 *
 * `R3` §3.5 recorded stale statistics as a defect that **did not reproduce**, twice, and §8
 * and §9 both named the suspect:
 *
 * > 이 데이터셋에는 **skew가 없다.** 모든 학습자가 정확히 3000개씩, 18개월에 균등하게 갖는다. […]
 * > **내가 만든 생성기가 T4의 한 갈래를 통째로 가리고 있을 수 있다.**
 *
 * Reading `Generator.kt` confirms the shape: every learner gets exactly `attemptsPerLearner`
 * rows, items are chosen with `nextInt(items)`, and timestamps are spread evenly across the
 * window. **No skew in row counts, item popularity, or time.**
 *
 * That was a hypothesis with nothing behind it. This measures it.
 *
 * ## Why not simply add skew to the generator
 *
 * Because every number in `R2`, `R3` and `R4` was taken on the uniform dataset, and the seed
 * digests are pinned by a test so that "same bytes on another machine" means something.
 * Changing the generator would invalidate all of it to answer one question.
 *
 * **So the variable is isolated instead.** Two tables, same row count, same index, same
 * query — one uniform, one skewed — each measured with statistics present and absent. The
 * shipped dataset is not touched, and nothing already published moves.
 *
 * ## What "stale" means here, and why it is not just "before ANALYZE"
 *
 * `R3` §3.5's most useful finding was that **`CREATE INDEX` partly repairs what a bulk load
 * left stale**: it scans the whole table, so `reltuples` and `relpages` come back accurate
 * even though nothing analysed the column distributions. The state a bulk-loaded, indexed,
 * un-analysed table is really in is therefore *row count known, distribution unknown* — and
 * that is what is reproduced here by deleting from `pg_statistic` after the index is built,
 * rather than by simply not running `ANALYZE`.
 */
class StaleStatisticsSkewTest {

    companion object {
        private const val ROWS = 1_000_000
        private const val LEARNERS = 1_000

        /** The share of the table one learner holds in the skewed variant. */
        private const val HEAVY_SHARE = 0.30

        private lateinit var pg: PostgreSQLContainer

        @BeforeAll
        @JvmStatic
        fun startPostgres() {
            pg = PostgreSQLContainer(DockerImageName.parse(POSTGRES_IMAGE))
            pg.start()
        }

        @AfterAll
        @JvmStatic
        fun stopPostgres() {
            if (::pg.isInitialized) pg.stop()
        }
    }

    private fun connect(): Connection =
        DriverManager.getConnection(pg.jdbcUrl, pg.username, pg.password)

    private fun Connection.exec(sql: String) = createStatement().use { it.execute(sql) }

    private fun Connection.scalar(sql: String): String =
        createStatement().use { st -> st.executeQuery(sql).use { it.next(); it.getString(1) } }

    /**
     * One table of [ROWS] rows, indexed, in the state a bulk load leaves behind.
     *
     * @param skewed when true, learner 1 holds [HEAVY_SHARE] of the table and the rest share
     *   what is left. When false, every learner holds exactly the same number of rows — the
     *   shape `Generator.kt` produces.
     */
    private fun Connection.buildTable(name: String, skewed: Boolean) {
        exec("drop table if exists $name")
        exec(
            """
            create table $name (
                id           bigint generated by default as identity primary key,
                learner_id   integer not null,
                elapsed_ms   integer not null,
                attempted_at timestamptz not null
            )
            """.trimIndent(),
        )

        val learnerExpression =
            if (skewed) {
                // A step function rather than a smooth power law: the question is whether a
                // wrong estimate flips a plan, and one heavy value is the cleanest way to ask
                // it. A Zipf distribution would be more realistic and would make the finding
                // harder to attribute.
                "case when i <= ${(ROWS * HEAVY_SHARE).toInt()} then 1 " +
                    "else 2 + (i % ${LEARNERS - 1}) end"
            } else {
                "1 + (i % $LEARNERS)"
            }

        exec(
            """
            insert into $name (learner_id, elapsed_ms, attempted_at)
            select $learnerExpression,
                   4000 + (i % 26000),
                   timestamptz '2025-02-10 00:00:00+00' + (i % 46656000) * interval '1 second'
              from generate_series(1, $ROWS) as i
            """.trimIndent(),
        )

        // The index T4's remedy adds. Built AFTER the load, exactly as V2 is.
        exec("create index ix_$name on $name (learner_id, attempted_at)")

        // The state R3 §3.5 identified: CREATE INDEX has repaired reltuples, and nothing has
        // analysed the column distributions. Deleting from pg_statistic reproduces that
        // faithfully; skipping ANALYZE alone would not, because the index build already ran.
        exec("delete from pg_statistic where starelid = '$name'::regclass")
    }

    private class Plan(val node: String, val estimated: Long, val actual: Long, val ms: Double) {
        val error get() = if (actual == 0L) Double.NaN else estimated.toDouble() / actual
        override fun toString() =
            "%-28s est %8d  actual %8d  ratio %6.2fx  %8.1f ms".format(node, estimated, actual, error, ms)
    }

    /**
     * An aggregate rather than a `limit 20` read, deliberately.
     *
     * `R3` §3.5 measured `… where learner_id = ? order by attempted_at desc limit 20`, which
     * an index serves trivially at any selectivity — so no estimate, however wrong, could
     * change the plan. **The estimate has to be able to matter.** An average over every one of
     * a learner's rows is the cheapest query where 0.1 % and 30 % of a table call for
     * different plans.
     */
    private fun Connection.planFor(table: String, learnerId: Int): Plan {
        val text = createStatement().use { st ->
            st.executeQuery("explain (analyze, buffers) select avg(elapsed_ms) from $table where learner_id = $learnerId")
                .use { rs -> buildList { while (rs.next()) add(rs.getString(1)) } }
        }
        // The scan node is the deepest line mentioning the table; the aggregate above it has
        // its own row counts and they are not the ones this is about.
        val scanLine = text.first { it.contains(table) && (it.contains("Scan") || it.contains("Seq")) }
        return Plan(
            node = scanLine.trim().substringBefore("  (").substringBefore(" on ").trim() +
                if (scanLine.contains("Parallel")) " (parallel)" else "",
            estimated = Regex("rows=(\\d+)").find(scanLine)!!.groupValues[1].toLong(),
            actual = Regex("actual time=[^)]*?rows=(\\d+)").find(scanLine)!!.groupValues[1].toLong(),
            ms = Regex("Execution Time: ([0-9.]+) ms").find(text.joinToString("\n"))!!.groupValues[1].toDouble(),
        )
    }

    @Test
    fun `whether a uniform dataset can hide stale statistics`() {
        val rows = mutableListOf<Pair<String, Plan>>()

        connect().use { c ->
            listOf(false to "t4_uniform", true to "t4_skewed").forEach { (skewed, table) ->
                c.buildTable(table, skewed)

                // The learner the question is about: in the skewed table, the heavy one.
                val subject = 1
                val label = if (skewed) "skewed" else "uniform"

                rows += "$label, statistics deleted" to c.planFor(table, subject)
                c.exec("analyze $table")
                rows += "$label, after ANALYZE  " to c.planFor(table, subject)
            }

            println()
            println("T4-SKEW >>> $ROWS rows, $LEARNERS learners, index on (learner_id, attempted_at)")
            println("  the skewed variant gives learner 1 ${(HEAVY_SHARE * 100).toInt()}% of the table")
            println("  query: select avg(elapsed_ms) from <t> where learner_id = 1")
            println()
            rows.forEach { (label, plan) -> println("  %-28s %s".format(label, plan)) }
            println()
            println("  rows held by learner 1 -- uniform: ${c.scalar("select count(*) from t4_uniform where learner_id = 1")}" +
                "   skewed: ${c.scalar("select count(*) from t4_skewed where learner_id = 1")}")
            println()
        }

        val byLabel = rows.toMap()
        val uniformBefore = byLabel.keys.first { it.startsWith("uniform, statistics") }
        val uniformAfter = byLabel.keys.first { it.startsWith("uniform, after") }

        // THE CONTROL. R3 §3.5 measured the plan not changing on a uniform dataset. If that
        // stopped being true here, this test is measuring something other than skew and the
        // comparison beside it means nothing.
        assertTrue(
            byLabel.getValue(uniformBefore).node == byLabel.getValue(uniformAfter).node,
            "the uniform table changed plan across ANALYZE, which R3 §3.5 measured it not " +
                "doing. Something other than skew is varying: ${byLabel.getValue(uniformBefore)} " +
                "then ${byLabel.getValue(uniformAfter)}",
        )

        // Nothing is asserted about the skewed arm. Whether the plan flips is the finding,
        // and a test that required it to flip would be a test that reports the answer it was
        // written to get -- R5 §9.
        assertTrue(rows.size == 4, "not every arm was measured")
    }
}
